export const products = [
   { code: "100",
    model: "Dacia",
    description: "Rola cauciuc fara insertie metalica",
    },
    { code: "200",
    model: "Renault",
    description: "Rola cauciuc cu insertie metalica",
    },
    { code: "201",
    model: "BMW",
    description: "Rola cauciuc",
    },
    { code: "300",
    model: "VOLVO",
    description: "Rola cauciuc simpla",
    },
    { code: "400",
    model: "Dacia",
    description: "Tambur  planetara",
    },
    { code: "501",
    model: "BMW",
    description: "Rola cauciuc",
    },
    { code: "600",
    model: "VOLVO",
    description: "Rola cauciuc simpla",
    },
    { code: "700",
    model: "Dacia",
    description: "Tambur  planetara",
    }
]